#!/usr/bin/env bash
# Script version
VERSION="0.4"

HOST=$1
PROP=$2
PORT=$3

function get_help() {
echo "zbx-ssl, version: $VERSION
(c) Khatsayuk Alexander, 2022

The script takes three positional parameters:
1 - hostname or it's IP address (example: www.google.com, 192.168.1.1)
2 - certificate property to retrieve in 'json', 'expire', 'serial', 'issuer' and 'fingerprint' (default: expire:days)
3 - port to connect (default: 443)

Examples:
# Retrieve certificate expiration date in unixtime:
zbx-ssl www.google.com expire
162356256
# Expiration date can be formated with prefixes 'days' and 'sec':
zbx-ssl www.google.com expire:days
42
# Retrieve certificate issuer:
zbx-ssl www.google.com issuer
CN=Google Internet Authority G3,O=Google Trust Services,C=US
# Retrieve all fields as JSON
zbx-ssl www.google.com json

Repository on GitHub: https://github.com/asand3r/zbx-ssl"
exit 0
}

# Set defaults
if [[ -z "$PROP" ]]; then PROP="expire"; fi
if [[ -z "$PORT" ]]; then PORT=443; fi
if [[ -z "$HOST" ]]; then get_help; fi

# Function gets cert expiration date in YYYY-m-d fromat
function get_cert_expire() {
  CERT_EXPIRE=$(true | timeout 5 openssl s_client -connect $1:$2 2>/dev/null | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f 2)
  if [[ -n "$CERT_EXPIRE" ]]
  then
    CERT_EXPIRE_UT=$(date --date="$CERT_EXPIRE" +%s)
    echo "$CERT_EXPIRE_UT"
  else
    echo "-1"
  fi
}

# Function returns certificate property
function get_cert_prop() {
  CERT_PROP=$(true | timeout 5 openssl s_client -connect $1:$2 2>/dev/null | openssl x509 -noout -$3 -nameopt RFC2253 2>/dev/null | sed -r "s/^[0-9a-zA-Z ]*=\s?//")
  if [[ -n "$CERT_PROP" ]]
  then
    echo "$CERT_PROP"
  else
    echo "-1"
  fi
}

function get_json() {
  if ! CERT_RAW_DATA=$(true | timeout 5 openssl s_client -connect $1:$2 2>/dev/null | openssl x509 -serial -fingerprint -enddate -issuer -noout -nameopt RFC2253 2>/dev/null)
  then
    echo "{\"ssl_error\": \"Unable to load certificate\": \"ssl_data\": {}}"
    exit 1
  fi

  SERIAL=$(echo "$CERT_RAW_DATA" | grep -oP 'serial=\K\w+')
  FINGERPRINT=$(echo "$CERT_RAW_DATA" | grep -oP 'Fingerprint=\K[\w:]*')
  ENDDATE_RAW=$(echo "$CERT_RAW_DATA" | grep -oP 'notAfter=\K[\w\d: ]*')
  ENDDATE_UNIXTIME=$(date -d"$ENDDATE_RAW" +%s)
  ENDDAYS=$(echo "(($ENDDATE_UNIXTIME - $(date +%s)) / 86400)" | bc)
  ENDSEC=$(echo "(($ENDDATE_UNIXTIME - $(date +%s)))" | bc)
  ISSUER=$(echo "$CERT_RAW_DATA" | grep -oP 'issuer=\K.*')

  echo "{\"ssl_error\": null, \"ssl_data\": {\"serial\": \"$SERIAL\", \"fingerprint\": \"$FINGERPRINT\", \
      \"enddate\": \"$ENDDATE_RAW\", \"enddate_unixtime\": \"$ENDDATE_UNIXTIME\", \"enddays\": \"$ENDDAYS\", \
      \"endsec\": \"$ENDSEC\", \"issuer\": \"$ISSUER\"}}"
}

case "$1" in
  "-h"|"--help")
    get_help
    ;;
esac

# Param to display
if [[ "$PROP" =~ ^expire ]]
then
  EXPIRE_FMT=$(echo "$PROP" | cut -d":" -f 2)
  EXPIRE=$(get_cert_expire $HOST $PORT)
  case "$EXPIRE_FMT" in
    days*)
      SCALE=$(echo "$EXPIRE_FMT" | cut -d "/" -f 2)
      if [[ -z "$SCALE" ]]; then SCALE=4; fi
      echo "scale=$SCALE; (($EXPIRE - $(date +%s)) / 86400)" | bc -l
      ;;
    "sec")
      echo $(($EXPIRE - $(date +%s)))
      ;;
    "utc")
      echo $(date -d @"$EXPIRE" --utc)
      ;;
    "iso-8601")
      echo $(date -d @"$EXPIRE" --iso-8601)
      ;;
    *)
      echo "$EXPIRE"
      ;;
   esac
elif [[ "$PROP" =~ ^(serial|issuer|fingerprint)$ ]]
then
  echo $(get_cert_prop $HOST $PORT $PROP)
elif [[ "$PROP" == "json" ]]
then
    echo $(get_json $HOST $PORT)
else
  get_help
fi
exit 0
